# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.cache/wt} [current_project]
set_property parent.project_path {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/FA.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/BCD_to7Seg.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/AddSub_8bit.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/time_multiplexer.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/Register.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/InstructionDecoder.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/digit_Sep.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/ControlUnit.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/ALU.v}
  {C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/project_final.srcs/sources_1/new/tempTOP.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/NexysA7-100t.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/angry/Desktop/hmwk/year 3 semester 2/CECS 361/projects/project_final/NexysA7-100t.xdc}}]


synth_design -top TOP -part xc7a100tcsg324-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
